{
    "name":"Fox",
    "tokens":[
        {
            "symbol":"WTRX",
            "address":"TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR",
            "chainId":1,
            "decimals":6,
            "name":"Wrapped TRX",
            "logoURI":"https://coin.top/production/upload/logo/TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR.png"
        },
        {
            "symbol":"USDT",
            "address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
            "chainId":1,
            "decimals":6,
            "name":"Tether USD",
            "logoURI":"https://coin.top/production/logo/usdtlogo.png"
        },
        {
            "symbol":"FOX",
            "address":"TEgxhyHLeqZitwBXHgw82pWyy4Sc8oMcL3",
            "chainId":1,
            "decimals":6,
            "name":"FoxCoin",
            "logoURI":"https://static.tronscan.org/production/upload/logo/new/TEgxhyHLeqZitwBXHgw82pWyy4Sc8oMcL3.png"
        }
    ],
    "logoURI":"https://static.tronscan.org/production/upload/logo/new/TEgxhyHLeqZitwBXHgw82pWyy4Sc8oMcL3.png",
    "version":{
        "patch":0,
        "major":1,
        "minor":0
    },
    "timestamp":1727538985000
}
