{
    "name":"Fox",
    "tokens":[
        {
            "symbol":"FOX",
            "address":"TEgxhyHLeqZitwBXHgw82pWyy4Sc8oMcL3",
            "chainId":1,
            "decimals":6,
            "name":"FoxCoin",
            "logoURI":"https://static.tronscan.org/production/upload/logo/new/TEgxhyHLeqZitwBXHgw82pWyy4Sc8oMcL3.png"
        } 
    ],
    "logoURI":"https://static.tronscan.org/production/upload/logo/new/TEgxhyHLeqZitwBXHgw82pWyy4Sc8oMcL3.png",
    "version":{
        "patch":0,
        "major":1,
        "minor":0
    },
    "timestamp":1727538740000
}
